### ISSUE TITLE
Proof of stake basics

### ISSUE THREAD

**Issue by azarovh** [mintlayer/mintlayer-core#697]
This issue is created to track progress and to document issues related to the proof of stake.
Ordered by highest priority first.

- [x] Finalize #260 with initial PoS implementation
- [x] Use pool balance for PoS target check
- [x] Store EpochData
- [x] Unit tests
- [x] Add Uint512 type
- [x] Spending stake output on block production #734
- [x] Support target calculation and retargeting
- [x] Decommission pool
- [x] Get rid of `OutputValue` in `TxOutput`, and make `TxOutput` itself an enum instead of using `OutputPurpose`, because we expect some output purpose types not to have value associated with them; e.g., accounting utxos.
- [x] (low priority due to release deadline) TransactionVerifier needs another look to be made smaller, more manageable and more testable
- [x] Stake delegations subscription
- [x] Stake delegations cancelling
- [x] #834
- [x] Reconsider the longest chain rule #827 
- [x] #752
- [x] #787
